return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "lua",
      "erlang",
      "elixir",
      "heex",
      "php",
      "javascript",
      "typescript",
      "tsx",
      "json",
      "html",
      "css",
      "scss",
      "go",
      "gomod",
      "gosum",
      "c_sharp",
      "cpp",
      "dockerfile",
      "fish",
      "graphql",
      "java",
      "kotlin",
      "markdown",
      "python",
      "sql",
      "swift",
      "yaml",
    },
  },
}
